/**
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Any Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.AnyMove#getMove <em>Move</em>}</li>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.AnyMove#getRemarks <em>Remarks</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getAnyMove()
 * @model
 * @generated
 */
public interface AnyMove extends EObject
{
  /**
   * Returns the value of the '<em><b>Move</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Move</em>' containment reference.
   * @see #setMove(DSLMove)
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getAnyMove_Move()
   * @model containment="true"
   * @generated
   */
  DSLMove getMove();

  /**
   * Sets the value of the '{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.AnyMove#getMove <em>Move</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Move</em>' containment reference.
   * @see #getMove()
   * @generated
   */
  void setMove(DSLMove value);

  /**
   * Returns the value of the '<em><b>Remarks</b></em>' attribute list.
   * The list contents are of type {@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.Remark}.
   * The literals are from the enumeration {@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.Remark}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Remarks</em>' attribute list.
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.Remark
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getAnyMove_Remarks()
   * @model unique="false"
   * @generated
   */
  EList<Remark> getRemarks();

} // AnyMove
