/**
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Checkmate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.Checkmate#getPlayer1 <em>Player1</em>}</li>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.Checkmate#getPlayer2 <em>Player2</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getCheckmate()
 * @model
 * @generated
 */
public interface Checkmate extends EObject
{
  /**
   * Returns the value of the '<em><b>Player1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Player1</em>' containment reference.
   * @see #setPlayer1(PlayerOrColor)
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getCheckmate_Player1()
   * @model containment="true"
   * @generated
   */
  PlayerOrColor getPlayer1();

  /**
   * Sets the value of the '{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.Checkmate#getPlayer1 <em>Player1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Player1</em>' containment reference.
   * @see #getPlayer1()
   * @generated
   */
  void setPlayer1(PlayerOrColor value);

  /**
   * Returns the value of the '<em><b>Player2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Player2</em>' containment reference.
   * @see #setPlayer2(PlayerOrColor)
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getCheckmate_Player2()
   * @model containment="true"
   * @generated
   */
  PlayerOrColor getPlayer2();

  /**
   * Sets the value of the '{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.Checkmate#getPlayer2 <em>Player2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Player2</em>' containment reference.
   * @see #getPlayer2()
   * @generated
   */
  void setPlayer2(PlayerOrColor value);

} // Checkmate
