/**
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Placement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.Placement#getPiece <em>Piece</em>}</li>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.Placement#getSquare <em>Square</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getPlacement()
 * @model
 * @generated
 */
public interface Placement extends EObject
{
  /**
   * Returns the value of the '<em><b>Piece</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Piece</em>' containment reference.
   * @see #setPiece(CustomPiece)
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getPlacement_Piece()
   * @model containment="true"
   * @generated
   */
  CustomPiece getPiece();

  /**
   * Sets the value of the '{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.Placement#getPiece <em>Piece</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Piece</em>' containment reference.
   * @see #getPiece()
   * @generated
   */
  void setPiece(CustomPiece value);

  /**
   * Returns the value of the '<em><b>Square</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Square</em>' containment reference.
   * @see #setSquare(Square)
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getPlacement_Square()
   * @model containment="true"
   * @generated
   */
  Square getSquare();

  /**
   * Sets the value of the '{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.Placement#getSquare <em>Square</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Square</em>' containment reference.
   * @see #getSquare()
   * @generated
   */
  void setSquare(Square value);

} // Placement
