/**
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SAN Move</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getSANMove()
 * @model
 * @generated
 */
public interface SANMove extends EObject
{
} // SANMove
