/**
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SAN Normal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getPiece <em>Piece</em>}</li>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getDisamb <em>Disamb</em>}</li>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getCapture <em>Capture</em>}</li>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getTarget <em>Target</em>}</li>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getPromotion <em>Promotion</em>}</li>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getCheck <em>Check</em>}</li>
 *   <li>{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getRemark <em>Remark</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getSANNormal()
 * @model
 * @generated
 */
public interface SANNormal extends EObject
{
  /**
   * Returns the value of the '<em><b>Piece</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Piece</em>' containment reference.
   * @see #setPiece(SANPiece)
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getSANNormal_Piece()
   * @model containment="true"
   * @generated
   */
  SANPiece getPiece();

  /**
   * Sets the value of the '{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getPiece <em>Piece</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Piece</em>' containment reference.
   * @see #getPiece()
   * @generated
   */
  void setPiece(SANPiece value);

  /**
   * Returns the value of the '<em><b>Disamb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Disamb</em>' containment reference.
   * @see #setDisamb(SANDisambiguation)
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getSANNormal_Disamb()
   * @model containment="true"
   * @generated
   */
  SANDisambiguation getDisamb();

  /**
   * Sets the value of the '{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getDisamb <em>Disamb</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Disamb</em>' containment reference.
   * @see #getDisamb()
   * @generated
   */
  void setDisamb(SANDisambiguation value);

  /**
   * Returns the value of the '<em><b>Capture</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capture</em>' containment reference.
   * @see #setCapture(SANCapture)
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getSANNormal_Capture()
   * @model containment="true"
   * @generated
   */
  SANCapture getCapture();

  /**
   * Sets the value of the '{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getCapture <em>Capture</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Capture</em>' containment reference.
   * @see #getCapture()
   * @generated
   */
  void setCapture(SANCapture value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference.
   * @see #setTarget(Square)
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getSANNormal_Target()
   * @model containment="true"
   * @generated
   */
  Square getTarget();

  /**
   * Sets the value of the '{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getTarget <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' containment reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Square value);

  /**
   * Returns the value of the '<em><b>Promotion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Promotion</em>' containment reference.
   * @see #setPromotion(SANPromotion)
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getSANNormal_Promotion()
   * @model containment="true"
   * @generated
   */
  SANPromotion getPromotion();

  /**
   * Sets the value of the '{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getPromotion <em>Promotion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Promotion</em>' containment reference.
   * @see #getPromotion()
   * @generated
   */
  void setPromotion(SANPromotion value);

  /**
   * Returns the value of the '<em><b>Check</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Check</em>' containment reference.
   * @see #setCheck(SANCheckMarker)
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getSANNormal_Check()
   * @model containment="true"
   * @generated
   */
  SANCheckMarker getCheck();

  /**
   * Sets the value of the '{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getCheck <em>Check</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Check</em>' containment reference.
   * @see #getCheck()
   * @generated
   */
  void setCheck(SANCheckMarker value);

  /**
   * Returns the value of the '<em><b>Remark</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Remark</em>' containment reference.
   * @see #setRemark(SANRemark)
   * @see uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getSANNormal_Remark()
   * @model containment="true"
   * @generated
   */
  SANRemark getRemark();

  /**
   * Sets the value of the '{@link uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANNormal#getRemark <em>Remark</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Remark</em>' containment reference.
   * @see #getRemark()
   * @generated
   */
  void setRemark(SANRemark value);

} // SANNormal
