/**
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Checkmate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.Checkmate#getPlayer1 <em>Player1</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.Checkmate#getPlayer2 <em>Player2</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getCheckmate()
 * @model
 * @generated
 */
public interface Checkmate extends Win
{
  /**
   * Returns the value of the '<em><b>Player1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Player1</em>' reference.
   * @see #setPlayer1(Player)
   * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getCheckmate_Player1()
   * @model
   * @generated
   */
  Player getPlayer1();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.Checkmate#getPlayer1 <em>Player1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Player1</em>' reference.
   * @see #getPlayer1()
   * @generated
   */
  void setPlayer1(Player value);

  /**
   * Returns the value of the '<em><b>Player2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Player2</em>' reference.
   * @see #setPlayer2(Player)
   * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getCheckmate_Player2()
   * @model
   * @generated
   */
  Player getPlayer2();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.Checkmate#getPlayer2 <em>Player2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Player2</em>' reference.
   * @see #getPlayer2()
   * @generated
   */
  void setPlayer2(Player value);

} // Checkmate
