/**
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Custom Positions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.CustomPositions#getPlacement <em>Placement</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getCustomPositions()
 * @model
 * @generated
 */
public interface CustomPositions extends EObject
{
  /**
   * Returns the value of the '<em><b>Placement</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.Placement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Placement</em>' containment reference list.
   * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getCustomPositions_Placement()
   * @model containment="true"
   * @generated
   */
  EList<Placement> getPlacement();

} // CustomPositions
