/**
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>En Passant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.EnPassant#getCapture <em>Capture</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.EnPassant#getSquare <em>Square</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getEnPassant()
 * @model
 * @generated
 */
public interface EnPassant extends DSLMove
{
  /**
   * Returns the value of the '<em><b>Capture</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capture</em>' containment reference.
   * @see #setCapture(Capture)
   * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getEnPassant_Capture()
   * @model containment="true"
   * @generated
   */
  Capture getCapture();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.EnPassant#getCapture <em>Capture</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Capture</em>' containment reference.
   * @see #getCapture()
   * @generated
   */
  void setCapture(Capture value);

  /**
   * Returns the value of the '<em><b>Square</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Square</em>' attribute.
   * @see #setSquare(String)
   * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getEnPassant_Square()
   * @model
   * @generated
   */
  String getSquare();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.EnPassant#getSquare <em>Square</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Square</em>' attribute.
   * @see #getSquare()
   * @generated
   */
  void setSquare(String value);

} // EnPassant
