/**
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Promotion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.Promotion#getMove <em>Move</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.Promotion#getPiece <em>Piece</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getPromotion()
 * @model
 * @generated
 */
public interface Promotion extends DSLMove
{
  /**
   * Returns the value of the '<em><b>Move</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Move</em>' containment reference.
   * @see #setMove(DSLMove)
   * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getPromotion_Move()
   * @model containment="true"
   * @generated
   */
  DSLMove getMove();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.Promotion#getMove <em>Move</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Move</em>' containment reference.
   * @see #getMove()
   * @generated
   */
  void setMove(DSLMove value);

  /**
   * Returns the value of the '<em><b>Piece</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.Piece}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Piece</em>' attribute.
   * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.Piece
   * @see #setPiece(Piece)
   * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getPromotion_Piece()
   * @model
   * @generated
   */
  Piece getPiece();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.Promotion#getPiece <em>Piece</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Piece</em>' attribute.
   * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.Piece
   * @see #getPiece()
   * @generated
   */
  void setPiece(Piece value);

} // Promotion
