/**
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Time Up</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.TimeUp#getPlayer <em>Player</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getTimeUp()
 * @model
 * @generated
 */
public interface TimeUp extends Win
{
  /**
   * Returns the value of the '<em><b>Player</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Player</em>' reference.
   * @see #setPlayer(Player)
   * @see uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage#getTimeUp_Player()
   * @model
   * @generated
   */
  Player getPlayer();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nerosiegfried.chessdsl.chessDSL.TimeUp#getPlayer <em>Player</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Player</em>' reference.
   * @see #getPlayer()
   * @generated
   */
  void setPlayer(Player value);

} // TimeUp
