/*
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.nerosiegfried.chessdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSLRuntimeModule;
import uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ChessDSLIdeSetup extends ChessDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ChessDSLRuntimeModule(), new ChessDSLIdeModule()));
	}
	
}
