/*
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.inf.nerosiegfried.chessdsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ChessDSLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Model");
		private final Assignment cGameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cGameGameParserRuleCall_0 = (RuleCall)cGameAssignment.eContents().get(0);
		
		//Model:
		//    game=Game
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//game=Game
		public Assignment getGameAssignment() { return cGameAssignment; }
		
		//Game
		public RuleCall getGameGameParserRuleCall_0() { return cGameGameParserRuleCall_0; }
	}
	public class GameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Game");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitleSTRINGTerminalRuleCall_1_0 = (RuleCall)cTitleAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cPlayersKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cPlayersAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cPlayersPlayerParserRuleCall_2_1_0 = (RuleCall)cPlayersAssignment_2_1.eContents().get(0);
		private final Assignment cInitialAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cInitialInitialStateParserRuleCall_3_0 = (RuleCall)cInitialAssignment_3.eContents().get(0);
		private final Keyword cMovesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cMovesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cMovesMovePairParserRuleCall_5_0 = (RuleCall)cMovesAssignment_5.eContents().get(0);
		private final Keyword cEndKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cConclusionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cConclusionConclusionParserRuleCall_7_0 = (RuleCall)cConclusionAssignment_7.eContents().get(0);
		
		//Game:
		//    'Game' title=STRING
		//    ('Players:' players+=Player+)?
		//    (initial=InitialState)?
		//    'Moves:' moves+=MovePair+
		//    'end'
		//    (conclusion=Conclusion)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Game' title=STRING
		//('Players:' players+=Player+)?
		//(initial=InitialState)?
		//'Moves:' moves+=MovePair+
		//'end'
		//(conclusion=Conclusion)?
		public Group getGroup() { return cGroup; }
		
		//'Game'
		public Keyword getGameKeyword_0() { return cGameKeyword_0; }
		
		//title=STRING
		public Assignment getTitleAssignment_1() { return cTitleAssignment_1; }
		
		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_1_0() { return cTitleSTRINGTerminalRuleCall_1_0; }
		
		//('Players:' players+=Player+)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'Players:'
		public Keyword getPlayersKeyword_2_0() { return cPlayersKeyword_2_0; }
		
		//players+=Player+
		public Assignment getPlayersAssignment_2_1() { return cPlayersAssignment_2_1; }
		
		//Player
		public RuleCall getPlayersPlayerParserRuleCall_2_1_0() { return cPlayersPlayerParserRuleCall_2_1_0; }
		
		//(initial=InitialState)?
		public Assignment getInitialAssignment_3() { return cInitialAssignment_3; }
		
		//InitialState
		public RuleCall getInitialInitialStateParserRuleCall_3_0() { return cInitialInitialStateParserRuleCall_3_0; }
		
		//'Moves:'
		public Keyword getMovesKeyword_4() { return cMovesKeyword_4; }
		
		//moves+=MovePair+
		public Assignment getMovesAssignment_5() { return cMovesAssignment_5; }
		
		//MovePair
		public RuleCall getMovesMovePairParserRuleCall_5_0() { return cMovesMovePairParserRuleCall_5_0; }
		
		//'end'
		public Keyword getEndKeyword_6() { return cEndKeyword_6; }
		
		//(conclusion=Conclusion)?
		public Assignment getConclusionAssignment_7() { return cConclusionAssignment_7; }
		
		//Conclusion
		public RuleCall getConclusionConclusionParserRuleCall_7_0() { return cConclusionConclusionParserRuleCall_7_0; }
	}
	public class PlayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Player");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cColorAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cColorColorEnumRuleCall_0_0 = (RuleCall)cColorAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Player:
		//    color=Color ':' name=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//color=Color ':' name=STRING
		public Group getGroup() { return cGroup; }
		
		//color=Color
		public Assignment getColorAssignment_0() { return cColorAssignment_0; }
		
		//Color
		public RuleCall getColorColorEnumRuleCall_0_0() { return cColorColorEnumRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
	}
	public class InitialStateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.InitialState");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInitialStateAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cInitialStateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Keyword cFreshKeyword_2_0 = (Keyword)cAlternatives_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Keyword cCustomKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cPositionsAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cPositionsCustomPositionsParserRuleCall_2_1_1_0 = (RuleCall)cPositionsAssignment_2_1_1.eContents().get(0);
		
		//InitialState:
		//    {InitialState}
		//    'InitialState' ('fresh' | 'custom' positions=CustomPositions)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{InitialState}
		//'InitialState' ('fresh' | 'custom' positions=CustomPositions)?
		public Group getGroup() { return cGroup; }
		
		//{InitialState}
		public Action getInitialStateAction_0() { return cInitialStateAction_0; }
		
		//'InitialState'
		public Keyword getInitialStateKeyword_1() { return cInitialStateKeyword_1; }
		
		//('fresh' | 'custom' positions=CustomPositions)?
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//'fresh'
		public Keyword getFreshKeyword_2_0() { return cFreshKeyword_2_0; }
		
		//'custom' positions=CustomPositions
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'custom'
		public Keyword getCustomKeyword_2_1_0() { return cCustomKeyword_2_1_0; }
		
		//positions=CustomPositions
		public Assignment getPositionsAssignment_2_1_1() { return cPositionsAssignment_2_1_1; }
		
		//CustomPositions
		public RuleCall getPositionsCustomPositionsParserRuleCall_2_1_1_0() { return cPositionsCustomPositionsParserRuleCall_2_1_1_0; }
	}
	public class CustomPositionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.CustomPositions");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCustomPositionsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPositionsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPlacementAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPlacementPlacementParserRuleCall_3_0 = (RuleCall)cPlacementAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//CustomPositions:
		//    {CustomPositions}
		//    'Positions:' '{'
		//        (placement+=Placement)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{CustomPositions}
		//'Positions:' '{'
		//    (placement+=Placement)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{CustomPositions}
		public Action getCustomPositionsAction_0() { return cCustomPositionsAction_0; }
		
		//'Positions:'
		public Keyword getPositionsKeyword_1() { return cPositionsKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(placement+=Placement)*
		public Assignment getPlacementAssignment_3() { return cPlacementAssignment_3; }
		
		//Placement
		public RuleCall getPlacementPlacementParserRuleCall_3_0() { return cPlacementPlacementParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class PlacementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Placement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPieceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPieceCustomPieceParserRuleCall_0_0 = (RuleCall)cPieceAssignment_0.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cOnKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cSquareAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSquareSquareParserRuleCall_2_0 = (RuleCall)cSquareAssignment_2.eContents().get(0);
		
		//Placement:
		//    //e.g., "WhiteKing on e1" or "BlackPawn = a7"
		//    piece=CustomPiece ('=' | 'on') square=Square
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////e.g., "WhiteKing on e1" or "BlackPawn = a7"
		//piece=CustomPiece ('=' | 'on') square=Square
		public Group getGroup() { return cGroup; }
		
		////e.g., "WhiteKing on e1" or "BlackPawn = a7"
		//piece=CustomPiece
		public Assignment getPieceAssignment_0() { return cPieceAssignment_0; }
		
		//CustomPiece
		public RuleCall getPieceCustomPieceParserRuleCall_0_0() { return cPieceCustomPieceParserRuleCall_0_0; }
		
		//('=' | 'on')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_1_0() { return cEqualsSignKeyword_1_0; }
		
		//'on'
		public Keyword getOnKeyword_1_1() { return cOnKeyword_1_1; }
		
		//square=Square
		public Assignment getSquareAssignment_2() { return cSquareAssignment_2; }
		
		//Square
		public RuleCall getSquareSquareParserRuleCall_2_0() { return cSquareSquareParserRuleCall_2_0; }
	}
	public class CustomPieceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.CustomPiece");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cColorAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cColorColorEnumRuleCall_0_0 = (RuleCall)cColorAssignment_0.eContents().get(0);
		private final Assignment cKindAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cKindPieceEnumRuleCall_1_0 = (RuleCall)cKindAssignment_1.eContents().get(0);
		
		//CustomPiece:
		//    (color=Color)
		//    (kind=Piece)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(color=Color)
		//(kind=Piece)
		public Group getGroup() { return cGroup; }
		
		//(color=Color)
		public Assignment getColorAssignment_0() { return cColorAssignment_0; }
		
		//Color
		public RuleCall getColorColorEnumRuleCall_0_0() { return cColorColorEnumRuleCall_0_0; }
		
		//(kind=Piece)
		public Assignment getKindAssignment_1() { return cKindAssignment_1; }
		
		//Piece
		public RuleCall getKindPieceEnumRuleCall_1_0() { return cKindPieceEnumRuleCall_1_0; }
	}
	public class MovePairElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.MovePair");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMoveNumberAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMoveNumberMOVENUMBERTerminalRuleCall_0_0 = (RuleCall)cMoveNumberAssignment_0.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Assignment cColor1Assignment_1_0_0 = (Assignment)cGroup_1_0.eContents().get(0);
		private final CrossReference cColor1PlayerCrossReference_1_0_0_0 = (CrossReference)cColor1Assignment_1_0_0.eContents().get(0);
		private final RuleCall cColor1PlayerIDTerminalRuleCall_1_0_0_0_1 = (RuleCall)cColor1PlayerCrossReference_1_0_0_0.eContents().get(1);
		private final Assignment cWhiteMoveAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cWhiteMoveAnyMoveParserRuleCall_1_0_1_0 = (RuleCall)cWhiteMoveAssignment_1_0_1.eContents().get(0);
		private final Keyword cFullStopFullStopFullStopKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cColor2Assignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final CrossReference cColor2PlayerCrossReference_2_0_0 = (CrossReference)cColor2Assignment_2_0.eContents().get(0);
		private final RuleCall cColor2PlayerIDTerminalRuleCall_2_0_0_1 = (RuleCall)cColor2PlayerCrossReference_2_0_0.eContents().get(1);
		private final Assignment cBlackMoveAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cBlackMoveAnyMoveParserRuleCall_2_1_0 = (RuleCall)cBlackMoveAssignment_2_1.eContents().get(0);
		
		//MovePair:
		//    //whiteMove can also be '...' when Black plays first in the position
		//    //or from where the records start. blackMove is optional depending on
		//    //where the records end or how the game itself ends
		//    moveNumber=MOVENUMBER
		//    (((color1=[Player])? whiteMove=AnyMove )| "...")
		//    ((color2=[Player])?blackMove=AnyMove)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////whiteMove can also be '...' when Black plays first in the position
		////or from where the records start. blackMove is optional depending on
		////where the records end or how the game itself ends
		//moveNumber=MOVENUMBER
		//(((color1=[Player])? whiteMove=AnyMove )| "...")
		//((color2=[Player])?blackMove=AnyMove)?
		public Group getGroup() { return cGroup; }
		
		////whiteMove can also be '...' when Black plays first in the position
		////or from where the records start. blackMove is optional depending on
		////where the records end or how the game itself ends
		//moveNumber=MOVENUMBER
		public Assignment getMoveNumberAssignment_0() { return cMoveNumberAssignment_0; }
		
		//MOVENUMBER
		public RuleCall getMoveNumberMOVENUMBERTerminalRuleCall_0_0() { return cMoveNumberMOVENUMBERTerminalRuleCall_0_0; }
		
		//(((color1=[Player])? whiteMove=AnyMove )| "...")
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//((color1=[Player])? whiteMove=AnyMove )
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//(color1=[Player])?
		public Assignment getColor1Assignment_1_0_0() { return cColor1Assignment_1_0_0; }
		
		//[Player]
		public CrossReference getColor1PlayerCrossReference_1_0_0_0() { return cColor1PlayerCrossReference_1_0_0_0; }
		
		//ID
		public RuleCall getColor1PlayerIDTerminalRuleCall_1_0_0_0_1() { return cColor1PlayerIDTerminalRuleCall_1_0_0_0_1; }
		
		//whiteMove=AnyMove
		public Assignment getWhiteMoveAssignment_1_0_1() { return cWhiteMoveAssignment_1_0_1; }
		
		//AnyMove
		public RuleCall getWhiteMoveAnyMoveParserRuleCall_1_0_1_0() { return cWhiteMoveAnyMoveParserRuleCall_1_0_1_0; }
		
		//"..."
		public Keyword getFullStopFullStopFullStopKeyword_1_1() { return cFullStopFullStopFullStopKeyword_1_1; }
		
		//((color2=[Player])?blackMove=AnyMove)?
		public Group getGroup_2() { return cGroup_2; }
		
		//(color2=[Player])?
		public Assignment getColor2Assignment_2_0() { return cColor2Assignment_2_0; }
		
		//[Player]
		public CrossReference getColor2PlayerCrossReference_2_0_0() { return cColor2PlayerCrossReference_2_0_0; }
		
		//ID
		public RuleCall getColor2PlayerIDTerminalRuleCall_2_0_0_1() { return cColor2PlayerIDTerminalRuleCall_2_0_0_1; }
		
		//blackMove=AnyMove
		public Assignment getBlackMoveAssignment_2_1() { return cBlackMoveAssignment_2_1; }
		
		//AnyMove
		public RuleCall getBlackMoveAnyMoveParserRuleCall_2_1_0() { return cBlackMoveAnyMoveParserRuleCall_2_1_0; }
	}
	public class AnyMoveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.AnyMove");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMoveAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMoveDSLMoveParserRuleCall_0_0 = (RuleCall)cMoveAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cRemarksAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRemarksRemarkEnumRuleCall_1_1_0 = (RuleCall)cRemarksAssignment_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//AnyMove:
		//    //for possible extensions to the language
		//    move=DSLMove ('(' remarks+=Remark* ')')?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////for possible extensions to the language
		//move=DSLMove ('(' remarks+=Remark* ')')?
		public Group getGroup() { return cGroup; }
		
		////for possible extensions to the language
		//move=DSLMove
		public Assignment getMoveAssignment_0() { return cMoveAssignment_0; }
		
		//DSLMove
		public RuleCall getMoveDSLMoveParserRuleCall_0_0() { return cMoveDSLMoveParserRuleCall_0_0; }
		
		//('(' remarks+=Remark* ')')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//remarks+=Remark*
		public Assignment getRemarksAssignment_1_1() { return cRemarksAssignment_1_1; }
		
		//Remark
		public RuleCall getRemarksRemarkEnumRuleCall_1_1_0() { return cRemarksRemarkEnumRuleCall_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class DSLMoveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.DSLMove");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMoveParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCaptureParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCastleParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cEnPassantParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cPromotionParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cDummyParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//DSLMove:
		//    Move | Capture | Castle | EnPassant | Promotion | Dummy
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Move | Capture | Castle | EnPassant | Promotion | Dummy
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Move
		public RuleCall getMoveParserRuleCall_0() { return cMoveParserRuleCall_0; }
		
		//Capture
		public RuleCall getCaptureParserRuleCall_1() { return cCaptureParserRuleCall_1; }
		
		//Castle
		public RuleCall getCastleParserRuleCall_2() { return cCastleParserRuleCall_2; }
		
		//EnPassant
		public RuleCall getEnPassantParserRuleCall_3() { return cEnPassantParserRuleCall_3; }
		
		//Promotion
		public RuleCall getPromotionParserRuleCall_4() { return cPromotionParserRuleCall_4; }
		
		//Dummy
		public RuleCall getDummyParserRuleCall_5() { return cDummyParserRuleCall_5; }
	}
	public class DummyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Dummy");
		private final Keyword cDummyKeyword = (Keyword)rule.eContents().get(1);
		
		//Dummy:
		//    'dummy'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'dummy'
		public Keyword getDummyKeyword() { return cDummyKeyword; }
	}
	public class MoveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Move");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMovesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPieceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPiecePieceEnumRuleCall_1_0 = (RuleCall)cPieceAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cFromAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cFromSquareParserRuleCall_2_0_1_0 = (RuleCall)cFromAssignment_2_0_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2_0_2 = (Keyword)cGroup_2_0.eContents().get(2);
		private final Assignment cToAssignment_2_0_3 = (Assignment)cGroup_2_0.eContents().get(3);
		private final RuleCall cToSquareParserRuleCall_2_0_3_0 = (RuleCall)cToAssignment_2_0_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_0_4 = (Keyword)cGroup_2_0.eContents().get(4);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Keyword cFromKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cFromAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cFromSquareParserRuleCall_2_1_1_0 = (RuleCall)cFromAssignment_2_1_1.eContents().get(0);
		private final Keyword cToKeyword_2_1_2 = (Keyword)cGroup_2_1.eContents().get(2);
		private final Assignment cToAssignment_2_1_3 = (Assignment)cGroup_2_1.eContents().get(3);
		private final RuleCall cToSquareParserRuleCall_2_1_3_0 = (RuleCall)cToAssignment_2_1_3.eContents().get(0);
		
		//Move:
		//    //Pawn(e2 -> e4), Knight from b1 to c3, etc.
		//    ('moves')?
		//    (piece=Piece)
		//    ('(' from=Square '->' to=Square ')'|
		//    'from' from=Square 'to' to=Square
		//    )
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////Pawn(e2 -> e4), Knight from b1 to c3, etc.
		//('moves')?
		//(piece=Piece)
		//('(' from=Square '->' to=Square ')'|
		//'from' from=Square 'to' to=Square
		//)
		public Group getGroup() { return cGroup; }
		
		////Pawn(e2 -> e4), Knight from b1 to c3, etc.
		//('moves')?
		public Keyword getMovesKeyword_0() { return cMovesKeyword_0; }
		
		//(piece=Piece)
		public Assignment getPieceAssignment_1() { return cPieceAssignment_1; }
		
		//Piece
		public RuleCall getPiecePieceEnumRuleCall_1_0() { return cPiecePieceEnumRuleCall_1_0; }
		
		//('(' from=Square '->' to=Square ')'|
		//'from' from=Square 'to' to=Square
		//)
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//'(' from=Square '->' to=Square ')'
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_0_0() { return cLeftParenthesisKeyword_2_0_0; }
		
		//from=Square
		public Assignment getFromAssignment_2_0_1() { return cFromAssignment_2_0_1; }
		
		//Square
		public RuleCall getFromSquareParserRuleCall_2_0_1_0() { return cFromSquareParserRuleCall_2_0_1_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_2_0_2() { return cHyphenMinusGreaterThanSignKeyword_2_0_2; }
		
		//to=Square
		public Assignment getToAssignment_2_0_3() { return cToAssignment_2_0_3; }
		
		//Square
		public RuleCall getToSquareParserRuleCall_2_0_3_0() { return cToSquareParserRuleCall_2_0_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_0_4() { return cRightParenthesisKeyword_2_0_4; }
		
		//'from' from=Square 'to' to=Square
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'from'
		public Keyword getFromKeyword_2_1_0() { return cFromKeyword_2_1_0; }
		
		//from=Square
		public Assignment getFromAssignment_2_1_1() { return cFromAssignment_2_1_1; }
		
		//Square
		public RuleCall getFromSquareParserRuleCall_2_1_1_0() { return cFromSquareParserRuleCall_2_1_1_0; }
		
		//'to'
		public Keyword getToKeyword_2_1_2() { return cToKeyword_2_1_2; }
		
		//to=Square
		public Assignment getToAssignment_2_1_3() { return cToAssignment_2_1_3; }
		
		//Square
		public RuleCall getToSquareParserRuleCall_2_1_3_0() { return cToSquareParserRuleCall_2_1_3_0; }
	}
	public class CaptureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Capture");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMoveAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMoveMoveParserRuleCall_0_0 = (RuleCall)cMoveAssignment_0.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cCaptureKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cCaptureAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cCapturePieceEnumRuleCall_1_0_1_0 = (RuleCall)cCaptureAssignment_1_0_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_0_2 = (Keyword)cGroup_1_0.eContents().get(2);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cAndKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Keyword cCapturesKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Assignment cCaptureAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final RuleCall cCapturePieceEnumRuleCall_1_1_2_0 = (RuleCall)cCaptureAssignment_1_1_2.eContents().get(0);
		
		//Capture:
		//    //An extension of a regular Move
		//    move=Move
		//    (('Capture(' capture=Piece ')')|
		//    (('and')? 'captures' capture=Piece))
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////An extension of a regular Move
		//move=Move
		//(('Capture(' capture=Piece ')')|
		//(('and')? 'captures' capture=Piece))
		public Group getGroup() { return cGroup; }
		
		////An extension of a regular Move
		//move=Move
		public Assignment getMoveAssignment_0() { return cMoveAssignment_0; }
		
		//Move
		public RuleCall getMoveMoveParserRuleCall_0_0() { return cMoveMoveParserRuleCall_0_0; }
		
		//(('Capture(' capture=Piece ')')|
		//(('and')? 'captures' capture=Piece))
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//('Capture(' capture=Piece ')')
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'Capture('
		public Keyword getCaptureKeyword_1_0_0() { return cCaptureKeyword_1_0_0; }
		
		//capture=Piece
		public Assignment getCaptureAssignment_1_0_1() { return cCaptureAssignment_1_0_1; }
		
		//Piece
		public RuleCall getCapturePieceEnumRuleCall_1_0_1_0() { return cCapturePieceEnumRuleCall_1_0_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_0_2() { return cRightParenthesisKeyword_1_0_2; }
		
		//(('and')? 'captures' capture=Piece)
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//('and')?
		public Keyword getAndKeyword_1_1_0() { return cAndKeyword_1_1_0; }
		
		//'captures'
		public Keyword getCapturesKeyword_1_1_1() { return cCapturesKeyword_1_1_1; }
		
		//capture=Piece
		public Assignment getCaptureAssignment_1_1_2() { return cCaptureAssignment_1_1_2; }
		
		//Piece
		public RuleCall getCapturePieceEnumRuleCall_1_1_2_0() { return cCapturePieceEnumRuleCall_1_1_2_0; }
	}
	public class CastleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Castle");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cCastleKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Alternatives cAlternatives_0_1 = (Alternatives)cGroup_0.eContents().get(1);
		private final Keyword cKingsideKeyword_0_1_0 = (Keyword)cAlternatives_0_1.eContents().get(0);
		private final Keyword cQueensideKeyword_0_1_1 = (Keyword)cAlternatives_0_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cCastlesKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Keyword cOnKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Keyword cTheKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Alternatives cAlternatives_1_2 = (Alternatives)cGroup_1.eContents().get(2);
		private final Keyword cKingsideKeyword_1_2_0 = (Keyword)cAlternatives_1_2.eContents().get(0);
		private final Keyword cQueensideKeyword_1_2_1 = (Keyword)cAlternatives_1_2.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Assignment cMoveAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cMoveMoveParserRuleCall_2_0_0 = (RuleCall)cMoveAssignment_2_0.eContents().get(0);
		private final Keyword cCastleKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Assignment cMoveAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cMoveMoveParserRuleCall_3_0_0 = (RuleCall)cMoveAssignment_3_0.eContents().get(0);
		private final Keyword cAndKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Keyword cCastlesKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		
		//Castle:
		//    ('Castle(' ('Kingside'|'Queenside') ')')|
		//    ('castles' ('on' 'the')? ('Kingside'|'Queenside'))|
		//    (move=Move 'Castle()')|
		//    (move=Move 'and' 'castles')
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('Castle(' ('Kingside'|'Queenside') ')')|
		//('castles' ('on' 'the')? ('Kingside'|'Queenside'))|
		//(move=Move 'Castle()')|
		//(move=Move 'and' 'castles')
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//('Castle(' ('Kingside'|'Queenside') ')')
		public Group getGroup_0() { return cGroup_0; }
		
		//'Castle('
		public Keyword getCastleKeyword_0_0() { return cCastleKeyword_0_0; }
		
		//('Kingside'|'Queenside')
		public Alternatives getAlternatives_0_1() { return cAlternatives_0_1; }
		
		//'Kingside'
		public Keyword getKingsideKeyword_0_1_0() { return cKingsideKeyword_0_1_0; }
		
		//'Queenside'
		public Keyword getQueensideKeyword_0_1_1() { return cQueensideKeyword_0_1_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }
		
		//('castles' ('on' 'the')? ('Kingside'|'Queenside'))
		public Group getGroup_1() { return cGroup_1; }
		
		//'castles'
		public Keyword getCastlesKeyword_1_0() { return cCastlesKeyword_1_0; }
		
		//('on' 'the')?
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//'on'
		public Keyword getOnKeyword_1_1_0() { return cOnKeyword_1_1_0; }
		
		//'the'
		public Keyword getTheKeyword_1_1_1() { return cTheKeyword_1_1_1; }
		
		//('Kingside'|'Queenside')
		public Alternatives getAlternatives_1_2() { return cAlternatives_1_2; }
		
		//'Kingside'
		public Keyword getKingsideKeyword_1_2_0() { return cKingsideKeyword_1_2_0; }
		
		//'Queenside'
		public Keyword getQueensideKeyword_1_2_1() { return cQueensideKeyword_1_2_1; }
		
		//(move=Move 'Castle()')
		public Group getGroup_2() { return cGroup_2; }
		
		//move=Move
		public Assignment getMoveAssignment_2_0() { return cMoveAssignment_2_0; }
		
		//Move
		public RuleCall getMoveMoveParserRuleCall_2_0_0() { return cMoveMoveParserRuleCall_2_0_0; }
		
		//'Castle()'
		public Keyword getCastleKeyword_2_1() { return cCastleKeyword_2_1; }
		
		//(move=Move 'and' 'castles')
		public Group getGroup_3() { return cGroup_3; }
		
		//move=Move
		public Assignment getMoveAssignment_3_0() { return cMoveAssignment_3_0; }
		
		//Move
		public RuleCall getMoveMoveParserRuleCall_3_0_0() { return cMoveMoveParserRuleCall_3_0_0; }
		
		//'and'
		public Keyword getAndKeyword_3_1() { return cAndKeyword_3_1; }
		
		//'castles'
		public Keyword getCastlesKeyword_3_2() { return cCastlesKeyword_3_2; }
	}
	public class EnPassantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.EnPassant");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCaptureAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cCaptureCaptureParserRuleCall_0_0 = (RuleCall)cCaptureAssignment_0.eContents().get(0);
		private final Keyword cOnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSquareAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSquareSquareParserRuleCall_2_0 = (RuleCall)cSquareAssignment_2.eContents().get(0);
		
		//EnPassant:
		//    //An extension of a Capture
		//    capture=Capture 'on' square=Square
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////An extension of a Capture
		//capture=Capture 'on' square=Square
		public Group getGroup() { return cGroup; }
		
		////An extension of a Capture
		//capture=Capture
		public Assignment getCaptureAssignment_0() { return cCaptureAssignment_0; }
		
		//Capture
		public RuleCall getCaptureCaptureParserRuleCall_0_0() { return cCaptureCaptureParserRuleCall_0_0; }
		
		//'on'
		public Keyword getOnKeyword_1() { return cOnKeyword_1; }
		
		//square=Square
		public Assignment getSquareAssignment_2() { return cSquareAssignment_2; }
		
		//Square
		public RuleCall getSquareSquareParserRuleCall_2_0() { return cSquareSquareParserRuleCall_2_0; }
	}
	public class PromotionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Promotion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMoveAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cMoveAlternatives_0_0 = (Alternatives)cMoveAssignment_0.eContents().get(0);
		private final RuleCall cMoveMoveParserRuleCall_0_0_0 = (RuleCall)cMoveAlternatives_0_0.eContents().get(0);
		private final RuleCall cMoveCaptureParserRuleCall_0_0_1 = (RuleCall)cMoveAlternatives_0_0.eContents().get(1);
		private final Keyword cPromotionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPieceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPiecePieceEnumRuleCall_2_0 = (RuleCall)cPieceAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Promotion:
		//    //e.g., promotes pawn to Queen on e8,
		//    //
		//    move=(Move|Capture) 'Promotion(' piece=Piece ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////e.g., promotes pawn to Queen on e8,
		////
		//move=(Move|Capture) 'Promotion(' piece=Piece ')'
		public Group getGroup() { return cGroup; }
		
		////e.g., promotes pawn to Queen on e8,
		////
		//move=(Move|Capture)
		public Assignment getMoveAssignment_0() { return cMoveAssignment_0; }
		
		//(Move|Capture)
		public Alternatives getMoveAlternatives_0_0() { return cMoveAlternatives_0_0; }
		
		//Move
		public RuleCall getMoveMoveParserRuleCall_0_0_0() { return cMoveMoveParserRuleCall_0_0_0; }
		
		//Capture
		public RuleCall getMoveCaptureParserRuleCall_0_0_1() { return cMoveCaptureParserRuleCall_0_0_1; }
		
		//'Promotion('
		public Keyword getPromotionKeyword_1() { return cPromotionKeyword_1; }
		
		//piece=Piece
		public Assignment getPieceAssignment_2() { return cPieceAssignment_2; }
		
		//Piece
		public RuleCall getPiecePieceEnumRuleCall_2_0() { return cPiecePieceEnumRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class ConclusionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Conclusion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMethodAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMethodMethodParserRuleCall_0_0 = (RuleCall)cMethodAssignment_0.eContents().get(0);
		private final Assignment cResultAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cResultResultParserRuleCall_1_0 = (RuleCall)cResultAssignment_1.eContents().get(0);
		
		//Conclusion:
		//    (method=Method)? result=Result
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(method=Method)? result=Result
		public Group getGroup() { return cGroup; }
		
		//(method=Method)?
		public Assignment getMethodAssignment_0() { return cMethodAssignment_0; }
		
		//Method
		public RuleCall getMethodMethodParserRuleCall_0_0() { return cMethodMethodParserRuleCall_0_0; }
		
		//result=Result
		public Assignment getResultAssignment_1() { return cResultAssignment_1; }
		
		//Result
		public RuleCall getResultResultParserRuleCall_1_0() { return cResultResultParserRuleCall_1_0; }
	}
	public class MethodElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Method");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cWinParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDrawParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Method:
		//    Win | Draw
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Win | Draw
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Win
		public RuleCall getWinParserRuleCall_0() { return cWinParserRuleCall_0; }
		
		//Draw
		public RuleCall getDrawParserRuleCall_1() { return cDrawParserRuleCall_1; }
	}
	public class WinElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Win");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTimeUpParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cResignParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCheckmateParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Win:
		//    TimeUp | Resign | Checkmate
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//TimeUp | Resign | Checkmate
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TimeUp
		public RuleCall getTimeUpParserRuleCall_0() { return cTimeUpParserRuleCall_0; }
		
		//Resign
		public RuleCall getResignParserRuleCall_1() { return cResignParserRuleCall_1; }
		
		//Checkmate
		public RuleCall getCheckmateParserRuleCall_2() { return cCheckmateParserRuleCall_2; }
	}
	public class TimeUpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.TimeUp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPlayerAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cPlayerPlayerCrossReference_0_0 = (CrossReference)cPlayerAssignment_0.eContents().get(0);
		private final RuleCall cPlayerPlayerIDTerminalRuleCall_0_0_1 = (RuleCall)cPlayerPlayerCrossReference_0_0.eContents().get(1);
		private final Keyword cRanKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cOutKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cOfKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cTimeKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//TimeUp:
		//    player=[Player] 'ran' 'out' 'of' 'time'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//player=[Player] 'ran' 'out' 'of' 'time'
		public Group getGroup() { return cGroup; }
		
		//player=[Player]
		public Assignment getPlayerAssignment_0() { return cPlayerAssignment_0; }
		
		//[Player]
		public CrossReference getPlayerPlayerCrossReference_0_0() { return cPlayerPlayerCrossReference_0_0; }
		
		//ID
		public RuleCall getPlayerPlayerIDTerminalRuleCall_0_0_1() { return cPlayerPlayerIDTerminalRuleCall_0_0_1; }
		
		//'ran'
		public Keyword getRanKeyword_1() { return cRanKeyword_1; }
		
		//'out'
		public Keyword getOutKeyword_2() { return cOutKeyword_2; }
		
		//'of'
		public Keyword getOfKeyword_3() { return cOfKeyword_3; }
		
		//'time'
		public Keyword getTimeKeyword_4() { return cTimeKeyword_4; }
	}
	public class ResignElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Resign");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPlayerAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cPlayerPlayerCrossReference_0_0 = (CrossReference)cPlayerAssignment_0.eContents().get(0);
		private final RuleCall cPlayerPlayerIDTerminalRuleCall_0_0_1 = (RuleCall)cPlayerPlayerCrossReference_0_0.eContents().get(1);
		private final Keyword cResignedKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Resign:
		//    player=[Player] 'resigned'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//player=[Player] 'resigned'
		public Group getGroup() { return cGroup; }
		
		//player=[Player]
		public Assignment getPlayerAssignment_0() { return cPlayerAssignment_0; }
		
		//[Player]
		public CrossReference getPlayerPlayerCrossReference_0_0() { return cPlayerPlayerCrossReference_0_0; }
		
		//ID
		public RuleCall getPlayerPlayerIDTerminalRuleCall_0_0_1() { return cPlayerPlayerIDTerminalRuleCall_0_0_1; }
		
		//'resigned'
		public Keyword getResignedKeyword_1() { return cResignedKeyword_1; }
	}
	public class CheckmateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Checkmate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPlayer1Assignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cPlayer1PlayerCrossReference_0_0 = (CrossReference)cPlayer1Assignment_0.eContents().get(0);
		private final RuleCall cPlayer1PlayerIDTerminalRuleCall_0_0_1 = (RuleCall)cPlayer1PlayerCrossReference_0_0.eContents().get(1);
		private final Keyword cCheckmatedKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPlayer2Assignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cPlayer2PlayerCrossReference_2_0 = (CrossReference)cPlayer2Assignment_2.eContents().get(0);
		private final RuleCall cPlayer2PlayerIDTerminalRuleCall_2_0_1 = (RuleCall)cPlayer2PlayerCrossReference_2_0.eContents().get(1);
		
		//Checkmate:
		//    player1=[Player] 'checkmated' player2=[Player]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//player1=[Player] 'checkmated' player2=[Player]
		public Group getGroup() { return cGroup; }
		
		//player1=[Player]
		public Assignment getPlayer1Assignment_0() { return cPlayer1Assignment_0; }
		
		//[Player]
		public CrossReference getPlayer1PlayerCrossReference_0_0() { return cPlayer1PlayerCrossReference_0_0; }
		
		//ID
		public RuleCall getPlayer1PlayerIDTerminalRuleCall_0_0_1() { return cPlayer1PlayerIDTerminalRuleCall_0_0_1; }
		
		//'checkmated'
		public Keyword getCheckmatedKeyword_1() { return cCheckmatedKeyword_1; }
		
		//player2=[Player]
		public Assignment getPlayer2Assignment_2() { return cPlayer2Assignment_2; }
		
		//[Player]
		public CrossReference getPlayer2PlayerCrossReference_2_0() { return cPlayer2PlayerCrossReference_2_0; }
		
		//ID
		public RuleCall getPlayer2PlayerIDTerminalRuleCall_2_0_1() { return cPlayer2PlayerIDTerminalRuleCall_2_0_1; }
	}
	public class DrawElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Draw");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPlayer1Assignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cPlayer1PlayerCrossReference_0_0 = (CrossReference)cPlayer1Assignment_0.eContents().get(0);
		private final RuleCall cPlayer1PlayerIDTerminalRuleCall_0_0_1 = (RuleCall)cPlayer1PlayerCrossReference_0_0.eContents().get(1);
		private final Keyword cAndKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPlayer2Assignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cPlayer2PlayerCrossReference_2_0 = (CrossReference)cPlayer2Assignment_2.eContents().get(0);
		private final RuleCall cPlayer2PlayerIDTerminalRuleCall_2_0_1 = (RuleCall)cPlayer2PlayerCrossReference_2_0.eContents().get(1);
		private final Assignment cResultAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Alternatives cResultAlternatives_3_0 = (Alternatives)cResultAssignment_3.eContents().get(0);
		private final RuleCall cResultStalemateParserRuleCall_3_0_0 = (RuleCall)cResultAlternatives_3_0.eContents().get(0);
		private final RuleCall cResultThreefoldParserRuleCall_3_0_1 = (RuleCall)cResultAlternatives_3_0.eContents().get(1);
		private final RuleCall cResultFiftyParserRuleCall_3_0_2 = (RuleCall)cResultAlternatives_3_0.eContents().get(2);
		private final RuleCall cResultAgreeParserRuleCall_3_0_3 = (RuleCall)cResultAlternatives_3_0.eContents().get(3);
		
		//Draw:
		//    player1=[Player] 'and' player2=[Player]
		//    result=(Stalemate|Threefold|Fifty|Agree)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//player1=[Player] 'and' player2=[Player]
		//result=(Stalemate|Threefold|Fifty|Agree)
		public Group getGroup() { return cGroup; }
		
		//player1=[Player]
		public Assignment getPlayer1Assignment_0() { return cPlayer1Assignment_0; }
		
		//[Player]
		public CrossReference getPlayer1PlayerCrossReference_0_0() { return cPlayer1PlayerCrossReference_0_0; }
		
		//ID
		public RuleCall getPlayer1PlayerIDTerminalRuleCall_0_0_1() { return cPlayer1PlayerIDTerminalRuleCall_0_0_1; }
		
		//'and'
		public Keyword getAndKeyword_1() { return cAndKeyword_1; }
		
		//player2=[Player]
		public Assignment getPlayer2Assignment_2() { return cPlayer2Assignment_2; }
		
		//[Player]
		public CrossReference getPlayer2PlayerCrossReference_2_0() { return cPlayer2PlayerCrossReference_2_0; }
		
		//ID
		public RuleCall getPlayer2PlayerIDTerminalRuleCall_2_0_1() { return cPlayer2PlayerIDTerminalRuleCall_2_0_1; }
		
		//result=(Stalemate|Threefold|Fifty|Agree)
		public Assignment getResultAssignment_3() { return cResultAssignment_3; }
		
		//(Stalemate|Threefold|Fifty|Agree)
		public Alternatives getResultAlternatives_3_0() { return cResultAlternatives_3_0; }
		
		//Stalemate
		public RuleCall getResultStalemateParserRuleCall_3_0_0() { return cResultStalemateParserRuleCall_3_0_0; }
		
		//Threefold
		public RuleCall getResultThreefoldParserRuleCall_3_0_1() { return cResultThreefoldParserRuleCall_3_0_1; }
		
		//Fifty
		public RuleCall getResultFiftyParserRuleCall_3_0_2() { return cResultFiftyParserRuleCall_3_0_2; }
		
		//Agree
		public RuleCall getResultAgreeParserRuleCall_3_0_3() { return cResultAgreeParserRuleCall_3_0_3; }
	}
	public class StalemateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Stalemate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEndedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTheKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cGameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cInKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cAKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cStalemateKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Stalemate returns EString:
		//    'ended' 'the' 'game' 'in' 'a' 'stalemate'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'ended' 'the' 'game' 'in' 'a' 'stalemate'
		public Group getGroup() { return cGroup; }
		
		//'ended'
		public Keyword getEndedKeyword_0() { return cEndedKeyword_0; }
		
		//'the'
		public Keyword getTheKeyword_1() { return cTheKeyword_1; }
		
		//'game'
		public Keyword getGameKeyword_2() { return cGameKeyword_2; }
		
		//'in'
		public Keyword getInKeyword_3() { return cInKeyword_3; }
		
		//'a'
		public Keyword getAKeyword_4() { return cAKeyword_4; }
		
		//'stalemate'
		public Keyword getStalemateKeyword_5() { return cStalemateKeyword_5; }
	}
	public class ThreefoldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Threefold");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRepeatedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPositionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cThreeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cTimesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Threefold returns EString:
		//    'repeated' 'a' 'position' 'three' 'times'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'repeated' 'a' 'position' 'three' 'times'
		public Group getGroup() { return cGroup; }
		
		//'repeated'
		public Keyword getRepeatedKeyword_0() { return cRepeatedKeyword_0; }
		
		//'a'
		public Keyword getAKeyword_1() { return cAKeyword_1; }
		
		//'position'
		public Keyword getPositionKeyword_2() { return cPositionKeyword_2; }
		
		//'three'
		public Keyword getThreeKeyword_3() { return cThreeKeyword_3; }
		
		//'times'
		public Keyword getTimesKeyword_4() { return cTimesKeyword_4; }
	}
	public class FiftyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Fifty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlayedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cFiftyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cMovesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cWithoutKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cAKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cCaptureKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Fifty returns EString:
		//    'played' 'fifty' 'moves' 'without' 'a' 'capture'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'played' 'fifty' 'moves' 'without' 'a' 'capture'
		public Group getGroup() { return cGroup; }
		
		//'played'
		public Keyword getPlayedKeyword_0() { return cPlayedKeyword_0; }
		
		//'fifty'
		public Keyword getFiftyKeyword_1() { return cFiftyKeyword_1; }
		
		//'moves'
		public Keyword getMovesKeyword_2() { return cMovesKeyword_2; }
		
		//'without'
		public Keyword getWithoutKeyword_3() { return cWithoutKeyword_3; }
		
		//'a'
		public Keyword getAKeyword_4() { return cAKeyword_4; }
		
		//'capture'
		public Keyword getCaptureKeyword_5() { return cCaptureKeyword_5; }
	}
	public class AgreeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Agree");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAgreedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cToKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDrawKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Agree returns EString:
		//    'agreed' 'to' 'a' 'draw'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'agreed' 'to' 'a' 'draw'
		public Group getGroup() { return cGroup; }
		
		//'agreed'
		public Keyword getAgreedKeyword_0() { return cAgreedKeyword_0; }
		
		//'to'
		public Keyword getToKeyword_1() { return cToKeyword_1; }
		
		//'a'
		public Keyword getAKeyword_2() { return cAKeyword_2; }
		
		//'draw'
		public Keyword getDrawKeyword_3() { return cDrawKeyword_3; }
	}
	public class ResultElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Result");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Alternatives cAlternatives_0_0 = (Alternatives)cGroup_0.eContents().get(0);
		private final Assignment cPlayerAssignment_0_0_0 = (Assignment)cAlternatives_0_0.eContents().get(0);
		private final CrossReference cPlayerPlayerCrossReference_0_0_0_0 = (CrossReference)cPlayerAssignment_0_0_0.eContents().get(0);
		private final RuleCall cPlayerPlayerIDTerminalRuleCall_0_0_0_0_1 = (RuleCall)cPlayerPlayerCrossReference_0_0_0_0.eContents().get(1);
		private final Assignment cColorAssignment_0_0_1 = (Assignment)cAlternatives_0_0.eContents().get(1);
		private final RuleCall cColorColorEnumRuleCall_0_0_1_0 = (RuleCall)cColorAssignment_0_0_1.eContents().get(0);
		private final Keyword cWinsKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Keyword cDrawKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//Result:
		//    ((player=[Player]|color=Color) 'wins')|
		//    ('draw')
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//((player=[Player]|color=Color) 'wins')|
		//('draw')
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//((player=[Player]|color=Color) 'wins')
		public Group getGroup_0() { return cGroup_0; }
		
		//(player=[Player]|color=Color)
		public Alternatives getAlternatives_0_0() { return cAlternatives_0_0; }
		
		//player=[Player]
		public Assignment getPlayerAssignment_0_0_0() { return cPlayerAssignment_0_0_0; }
		
		//[Player]
		public CrossReference getPlayerPlayerCrossReference_0_0_0_0() { return cPlayerPlayerCrossReference_0_0_0_0; }
		
		//ID
		public RuleCall getPlayerPlayerIDTerminalRuleCall_0_0_0_0_1() { return cPlayerPlayerIDTerminalRuleCall_0_0_0_0_1; }
		
		//color=Color
		public Assignment getColorAssignment_0_0_1() { return cColorAssignment_0_0_1; }
		
		//Color
		public RuleCall getColorColorEnumRuleCall_0_0_1_0() { return cColorColorEnumRuleCall_0_0_1_0; }
		
		//'wins'
		public Keyword getWinsKeyword_0_1() { return cWinsKeyword_0_1; }
		
		//('draw')
		public Keyword getDrawKeyword_1() { return cDrawKeyword_1; }
	}
	public class SquareElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Square");
		private final RuleCall cSQUARETERMINALTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Square:
		//    SQUARETERMINAL
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//SQUARETERMINAL
		public RuleCall getSQUARETERMINALTerminalRuleCall() { return cSQUARETERMINALTerminalRuleCall; }
	}
	
	public class RemarkElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Remark");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cGoodEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cGoodGoodKeyword_0_0 = (Keyword)cGoodEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBadEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBadBadKeyword_1_0 = (Keyword)cBadEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cExcellentEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cExcellentExcellentKeyword_2_0 = (Keyword)cExcellentEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cRiskyEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cRiskyRiskyKeyword_3_0 = (Keyword)cRiskyEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cDubiousEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cDubiousDubiousKeyword_4_0 = (Keyword)cDubiousEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cCheckEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cCheckCheckKeyword_5_0 = (Keyword)cCheckEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cCheckmateEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cCheckmateCheckmateKeyword_6_0 = (Keyword)cCheckmateEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum Remark:
		//    Good |
		//    Bad |
		//    Excellent |
		//    Risky |
		//    Dubious |
		//    Check |
		//    Checkmate
		//;
		public EnumRule getRule() { return rule; }
		
		//Good |
		//Bad |
		//Excellent |
		//Risky |
		//Dubious |
		//Check |
		//Checkmate
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Good
		public EnumLiteralDeclaration getGoodEnumLiteralDeclaration_0() { return cGoodEnumLiteralDeclaration_0; }
		
		public Keyword getGoodGoodKeyword_0_0() { return cGoodGoodKeyword_0_0; }
		
		//Bad
		public EnumLiteralDeclaration getBadEnumLiteralDeclaration_1() { return cBadEnumLiteralDeclaration_1; }
		
		public Keyword getBadBadKeyword_1_0() { return cBadBadKeyword_1_0; }
		
		//Excellent
		public EnumLiteralDeclaration getExcellentEnumLiteralDeclaration_2() { return cExcellentEnumLiteralDeclaration_2; }
		
		public Keyword getExcellentExcellentKeyword_2_0() { return cExcellentExcellentKeyword_2_0; }
		
		//Risky
		public EnumLiteralDeclaration getRiskyEnumLiteralDeclaration_3() { return cRiskyEnumLiteralDeclaration_3; }
		
		public Keyword getRiskyRiskyKeyword_3_0() { return cRiskyRiskyKeyword_3_0; }
		
		//Dubious
		public EnumLiteralDeclaration getDubiousEnumLiteralDeclaration_4() { return cDubiousEnumLiteralDeclaration_4; }
		
		public Keyword getDubiousDubiousKeyword_4_0() { return cDubiousDubiousKeyword_4_0; }
		
		//Check
		public EnumLiteralDeclaration getCheckEnumLiteralDeclaration_5() { return cCheckEnumLiteralDeclaration_5; }
		
		public Keyword getCheckCheckKeyword_5_0() { return cCheckCheckKeyword_5_0; }
		
		//Checkmate
		public EnumLiteralDeclaration getCheckmateEnumLiteralDeclaration_6() { return cCheckmateEnumLiteralDeclaration_6; }
		
		public Keyword getCheckmateCheckmateKeyword_6_0() { return cCheckmateCheckmateKeyword_6_0; }
	}
	public class ColorElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Color");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cWhiteEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cWhiteWhiteKeyword_0_0 = (Keyword)cWhiteEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBlackEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBlackBlackKeyword_1_0 = (Keyword)cBlackEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Color:
		//    White | Black
		//;
		public EnumRule getRule() { return rule; }
		
		//White | Black
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//White
		public EnumLiteralDeclaration getWhiteEnumLiteralDeclaration_0() { return cWhiteEnumLiteralDeclaration_0; }
		
		public Keyword getWhiteWhiteKeyword_0_0() { return cWhiteWhiteKeyword_0_0; }
		
		//Black
		public EnumLiteralDeclaration getBlackEnumLiteralDeclaration_1() { return cBlackEnumLiteralDeclaration_1; }
		
		public Keyword getBlackBlackKeyword_1_0() { return cBlackBlackKeyword_1_0; }
	}
	public class PieceElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.Piece");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cKingEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cKingKingKeyword_0_0 = (Keyword)cKingEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cQueenEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cQueenQueenKeyword_1_0 = (Keyword)cQueenEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cRookEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cRookRookKeyword_2_0 = (Keyword)cRookEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cBishopEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cBishopBishopKeyword_3_0 = (Keyword)cBishopEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cKnightEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cKnightKnightKeyword_4_0 = (Keyword)cKnightEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cPawnEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cPawnPawnKeyword_5_0 = (Keyword)cPawnEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum Piece:
		//    King  |
		//    Queen |
		//    Rook  |
		//    Bishop|
		//    Knight|
		//    Pawn
		//;
		public EnumRule getRule() { return rule; }
		
		//King  |
		//Queen |
		//Rook  |
		//Bishop|
		//Knight|
		//Pawn
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//King
		public EnumLiteralDeclaration getKingEnumLiteralDeclaration_0() { return cKingEnumLiteralDeclaration_0; }
		
		public Keyword getKingKingKeyword_0_0() { return cKingKingKeyword_0_0; }
		
		//Queen
		public EnumLiteralDeclaration getQueenEnumLiteralDeclaration_1() { return cQueenEnumLiteralDeclaration_1; }
		
		public Keyword getQueenQueenKeyword_1_0() { return cQueenQueenKeyword_1_0; }
		
		//Rook
		public EnumLiteralDeclaration getRookEnumLiteralDeclaration_2() { return cRookEnumLiteralDeclaration_2; }
		
		public Keyword getRookRookKeyword_2_0() { return cRookRookKeyword_2_0; }
		
		//Bishop
		public EnumLiteralDeclaration getBishopEnumLiteralDeclaration_3() { return cBishopEnumLiteralDeclaration_3; }
		
		public Keyword getBishopBishopKeyword_3_0() { return cBishopBishopKeyword_3_0; }
		
		//Knight
		public EnumLiteralDeclaration getKnightEnumLiteralDeclaration_4() { return cKnightEnumLiteralDeclaration_4; }
		
		public Keyword getKnightKnightKeyword_4_0() { return cKnightKnightKeyword_4_0; }
		
		//Pawn
		public EnumLiteralDeclaration getPawnEnumLiteralDeclaration_5() { return cPawnEnumLiteralDeclaration_5; }
		
		public Keyword getPawnPawnKeyword_5_0() { return cPawnPawnKeyword_5_0; }
	}
	
	private final ModelElements pModel;
	private final GameElements pGame;
	private final PlayerElements pPlayer;
	private final InitialStateElements pInitialState;
	private final CustomPositionsElements pCustomPositions;
	private final PlacementElements pPlacement;
	private final CustomPieceElements pCustomPiece;
	private final MovePairElements pMovePair;
	private final TerminalRule tMOVENUMBER;
	private final AnyMoveElements pAnyMove;
	private final DSLMoveElements pDSLMove;
	private final DummyElements pDummy;
	private final MoveElements pMove;
	private final CaptureElements pCapture;
	private final CastleElements pCastle;
	private final EnPassantElements pEnPassant;
	private final PromotionElements pPromotion;
	private final RemarkElements eRemark;
	private final ConclusionElements pConclusion;
	private final MethodElements pMethod;
	private final WinElements pWin;
	private final TimeUpElements pTimeUp;
	private final ResignElements pResign;
	private final CheckmateElements pCheckmate;
	private final DrawElements pDraw;
	private final StalemateElements pStalemate;
	private final ThreefoldElements pThreefold;
	private final FiftyElements pFifty;
	private final AgreeElements pAgree;
	private final ResultElements pResult;
	private final ColorElements eColor;
	private final PieceElements ePiece;
	private final SquareElements pSquare;
	private final TerminalRule tSQUARETERMINAL;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ChessDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pGame = new GameElements();
		this.pPlayer = new PlayerElements();
		this.pInitialState = new InitialStateElements();
		this.pCustomPositions = new CustomPositionsElements();
		this.pPlacement = new PlacementElements();
		this.pCustomPiece = new CustomPieceElements();
		this.pMovePair = new MovePairElements();
		this.tMOVENUMBER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.MOVENUMBER");
		this.pAnyMove = new AnyMoveElements();
		this.pDSLMove = new DSLMoveElements();
		this.pDummy = new DummyElements();
		this.pMove = new MoveElements();
		this.pCapture = new CaptureElements();
		this.pCastle = new CastleElements();
		this.pEnPassant = new EnPassantElements();
		this.pPromotion = new PromotionElements();
		this.eRemark = new RemarkElements();
		this.pConclusion = new ConclusionElements();
		this.pMethod = new MethodElements();
		this.pWin = new WinElements();
		this.pTimeUp = new TimeUpElements();
		this.pResign = new ResignElements();
		this.pCheckmate = new CheckmateElements();
		this.pDraw = new DrawElements();
		this.pStalemate = new StalemateElements();
		this.pThreefold = new ThreefoldElements();
		this.pFifty = new FiftyElements();
		this.pAgree = new AgreeElements();
		this.pResult = new ResultElements();
		this.eColor = new ColorElements();
		this.ePiece = new PieceElements();
		this.pSquare = new SquareElements();
		this.tSQUARETERMINAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL.SQUARETERMINAL");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("uk.ac.kcl.inf.nerosiegfried.chessdsl.ChessDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    game=Game
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Game:
	//    'Game' title=STRING
	//    ('Players:' players+=Player+)?
	//    (initial=InitialState)?
	//    'Moves:' moves+=MovePair+
	//    'end'
	//    (conclusion=Conclusion)?
	//;
	public GameElements getGameAccess() {
		return pGame;
	}
	
	public ParserRule getGameRule() {
		return getGameAccess().getRule();
	}
	
	//Player:
	//    color=Color ':' name=STRING
	//;
	public PlayerElements getPlayerAccess() {
		return pPlayer;
	}
	
	public ParserRule getPlayerRule() {
		return getPlayerAccess().getRule();
	}
	
	//InitialState:
	//    {InitialState}
	//    'InitialState' ('fresh' | 'custom' positions=CustomPositions)?
	//;
	public InitialStateElements getInitialStateAccess() {
		return pInitialState;
	}
	
	public ParserRule getInitialStateRule() {
		return getInitialStateAccess().getRule();
	}
	
	//CustomPositions:
	//    {CustomPositions}
	//    'Positions:' '{'
	//        (placement+=Placement)*
	//    '}'
	//;
	public CustomPositionsElements getCustomPositionsAccess() {
		return pCustomPositions;
	}
	
	public ParserRule getCustomPositionsRule() {
		return getCustomPositionsAccess().getRule();
	}
	
	//Placement:
	//    //e.g., "WhiteKing on e1" or "BlackPawn = a7"
	//    piece=CustomPiece ('=' | 'on') square=Square
	//;
	public PlacementElements getPlacementAccess() {
		return pPlacement;
	}
	
	public ParserRule getPlacementRule() {
		return getPlacementAccess().getRule();
	}
	
	//CustomPiece:
	//    (color=Color)
	//    (kind=Piece)
	//;
	public CustomPieceElements getCustomPieceAccess() {
		return pCustomPiece;
	}
	
	public ParserRule getCustomPieceRule() {
		return getCustomPieceAccess().getRule();
	}
	
	//MovePair:
	//    //whiteMove can also be '...' when Black plays first in the position
	//    //or from where the records start. blackMove is optional depending on
	//    //where the records end or how the game itself ends
	//    moveNumber=MOVENUMBER
	//    (((color1=[Player])? whiteMove=AnyMove )| "...")
	//    ((color2=[Player])?blackMove=AnyMove)?
	//;
	public MovePairElements getMovePairAccess() {
		return pMovePair;
	}
	
	public ParserRule getMovePairRule() {
		return getMovePairAccess().getRule();
	}
	
	//terminal MOVENUMBER:
	//    INT "."
	//;
	public TerminalRule getMOVENUMBERRule() {
		return tMOVENUMBER;
	}
	
	//AnyMove:
	//    //for possible extensions to the language
	//    move=DSLMove ('(' remarks+=Remark* ')')?
	//;
	public AnyMoveElements getAnyMoveAccess() {
		return pAnyMove;
	}
	
	public ParserRule getAnyMoveRule() {
		return getAnyMoveAccess().getRule();
	}
	
	//DSLMove:
	//    Move | Capture | Castle | EnPassant | Promotion | Dummy
	//;
	public DSLMoveElements getDSLMoveAccess() {
		return pDSLMove;
	}
	
	public ParserRule getDSLMoveRule() {
		return getDSLMoveAccess().getRule();
	}
	
	//Dummy:
	//    'dummy'
	//;
	public DummyElements getDummyAccess() {
		return pDummy;
	}
	
	public ParserRule getDummyRule() {
		return getDummyAccess().getRule();
	}
	
	//Move:
	//    //Pawn(e2 -> e4), Knight from b1 to c3, etc.
	//    ('moves')?
	//    (piece=Piece)
	//    ('(' from=Square '->' to=Square ')'|
	//    'from' from=Square 'to' to=Square
	//    )
	//;
	public MoveElements getMoveAccess() {
		return pMove;
	}
	
	public ParserRule getMoveRule() {
		return getMoveAccess().getRule();
	}
	
	//Capture:
	//    //An extension of a regular Move
	//    move=Move
	//    (('Capture(' capture=Piece ')')|
	//    (('and')? 'captures' capture=Piece))
	//;
	public CaptureElements getCaptureAccess() {
		return pCapture;
	}
	
	public ParserRule getCaptureRule() {
		return getCaptureAccess().getRule();
	}
	
	//Castle:
	//    ('Castle(' ('Kingside'|'Queenside') ')')|
	//    ('castles' ('on' 'the')? ('Kingside'|'Queenside'))|
	//    (move=Move 'Castle()')|
	//    (move=Move 'and' 'castles')
	//;
	public CastleElements getCastleAccess() {
		return pCastle;
	}
	
	public ParserRule getCastleRule() {
		return getCastleAccess().getRule();
	}
	
	//EnPassant:
	//    //An extension of a Capture
	//    capture=Capture 'on' square=Square
	//;
	public EnPassantElements getEnPassantAccess() {
		return pEnPassant;
	}
	
	public ParserRule getEnPassantRule() {
		return getEnPassantAccess().getRule();
	}
	
	//Promotion:
	//    //e.g., promotes pawn to Queen on e8,
	//    //
	//    move=(Move|Capture) 'Promotion(' piece=Piece ')'
	//;
	public PromotionElements getPromotionAccess() {
		return pPromotion;
	}
	
	public ParserRule getPromotionRule() {
		return getPromotionAccess().getRule();
	}
	
	//enum Remark:
	//    Good |
	//    Bad |
	//    Excellent |
	//    Risky |
	//    Dubious |
	//    Check |
	//    Checkmate
	//;
	public RemarkElements getRemarkAccess() {
		return eRemark;
	}
	
	public EnumRule getRemarkRule() {
		return getRemarkAccess().getRule();
	}
	
	//Conclusion:
	//    (method=Method)? result=Result
	//;
	public ConclusionElements getConclusionAccess() {
		return pConclusion;
	}
	
	public ParserRule getConclusionRule() {
		return getConclusionAccess().getRule();
	}
	
	//Method:
	//    Win | Draw
	//;
	public MethodElements getMethodAccess() {
		return pMethod;
	}
	
	public ParserRule getMethodRule() {
		return getMethodAccess().getRule();
	}
	
	//Win:
	//    TimeUp | Resign | Checkmate
	//;
	public WinElements getWinAccess() {
		return pWin;
	}
	
	public ParserRule getWinRule() {
		return getWinAccess().getRule();
	}
	
	//TimeUp:
	//    player=[Player] 'ran' 'out' 'of' 'time'
	//;
	public TimeUpElements getTimeUpAccess() {
		return pTimeUp;
	}
	
	public ParserRule getTimeUpRule() {
		return getTimeUpAccess().getRule();
	}
	
	//Resign:
	//    player=[Player] 'resigned'
	//;
	public ResignElements getResignAccess() {
		return pResign;
	}
	
	public ParserRule getResignRule() {
		return getResignAccess().getRule();
	}
	
	//Checkmate:
	//    player1=[Player] 'checkmated' player2=[Player]
	//;
	public CheckmateElements getCheckmateAccess() {
		return pCheckmate;
	}
	
	public ParserRule getCheckmateRule() {
		return getCheckmateAccess().getRule();
	}
	
	//Draw:
	//    player1=[Player] 'and' player2=[Player]
	//    result=(Stalemate|Threefold|Fifty|Agree)
	//;
	public DrawElements getDrawAccess() {
		return pDraw;
	}
	
	public ParserRule getDrawRule() {
		return getDrawAccess().getRule();
	}
	
	//Stalemate returns EString:
	//    'ended' 'the' 'game' 'in' 'a' 'stalemate'
	//;
	public StalemateElements getStalemateAccess() {
		return pStalemate;
	}
	
	public ParserRule getStalemateRule() {
		return getStalemateAccess().getRule();
	}
	
	//Threefold returns EString:
	//    'repeated' 'a' 'position' 'three' 'times'
	//;
	public ThreefoldElements getThreefoldAccess() {
		return pThreefold;
	}
	
	public ParserRule getThreefoldRule() {
		return getThreefoldAccess().getRule();
	}
	
	//Fifty returns EString:
	//    'played' 'fifty' 'moves' 'without' 'a' 'capture'
	//;
	public FiftyElements getFiftyAccess() {
		return pFifty;
	}
	
	public ParserRule getFiftyRule() {
		return getFiftyAccess().getRule();
	}
	
	//Agree returns EString:
	//    'agreed' 'to' 'a' 'draw'
	//;
	public AgreeElements getAgreeAccess() {
		return pAgree;
	}
	
	public ParserRule getAgreeRule() {
		return getAgreeAccess().getRule();
	}
	
	//Result:
	//    ((player=[Player]|color=Color) 'wins')|
	//    ('draw')
	//;
	public ResultElements getResultAccess() {
		return pResult;
	}
	
	public ParserRule getResultRule() {
		return getResultAccess().getRule();
	}
	
	//enum Color:
	//    White | Black
	//;
	public ColorElements getColorAccess() {
		return eColor;
	}
	
	public EnumRule getColorRule() {
		return getColorAccess().getRule();
	}
	
	//enum Piece:
	//    King  |
	//    Queen |
	//    Rook  |
	//    Bishop|
	//    Knight|
	//    Pawn
	//;
	public PieceElements getPieceAccess() {
		return ePiece;
	}
	
	public EnumRule getPieceRule() {
		return getPieceAccess().getRule();
	}
	
	//Square:
	//    SQUARETERMINAL
	//;
	public SquareElements getSquareAccess() {
		return pSquare;
	}
	
	public ParserRule getSquareRule() {
		return getSquareAccess().getRule();
	}
	
	//terminal SQUARETERMINAL:
	//    ('a'..'h'|'A'..'H')('1'..'8')
	//;
	public TerminalRule getSQUARETERMINALRule() {
		return tSQUARETERMINAL;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
