/*
 * generated by Xtext 2.32.0
 */
package uk.ac.kcl.in.nerosiegfried.chessdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ChessDSLUiModule extends AbstractChessDSLUiModule {

	public ChessDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
