/*
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.nerosiegfried.chessdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ChessDSLStandaloneSetup extends ChessDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new ChessDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
