/*
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.in.nerosiegfried.chessdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.nerosiegfried.chessdsl.ui.internal.ChessdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ChessDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ChessdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ChessdslActivator activator = ChessdslActivator.getInstance();
		return activator != null ? activator.getInjector(ChessdslActivator.UK_AC_KCL_IN_NEROSIEGFRIED_CHESSDSL_CHESSDSL) : null;
	}

}
