/*
 * generated by Xtext 2.32.0
 */
package uk.ac.kcl.in.nerosiegfried.chessdsl.ide;


/**
 * Use this class to register ide components.
 */
public class ChessDSLIdeModule extends AbstractChessDSLIdeModule {
}
