/**
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.ChessDSLPackage;
import uk.ac.kcl.in.nerosiegfried.chessdsl.chessDSL.SANCapture;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SAN Capture</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SANCaptureImpl extends MinimalEObjectImpl.Container implements SANCapture
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SANCaptureImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ChessDSLPackage.Literals.SAN_CAPTURE;
  }

} //SANCaptureImpl
